#blue
version: '3'
services:
  osogo:
    build: .
    ports:
      - "8082:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /home/ec2-user/log:/var/log
    container_name: spring-green