spring:
  config:
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8080

image:
  path: image/